name: AOTPRFYL
version: 1.5
main: fr.axicer.AOTPRFYL.AOTPRFYLMain

commands:
  left:
    description: Quitter la partie
    usage: /left
  start:
    description: Forcer le demarrage de la partie
    usage: /start